### ISSUE TITLE
base_dir

### ISSUE THREAD

**Issue by tairoroberto** [jansenfelipe/cnpj-gratis#12]
Cara tive o seguinte erro ao subir pro meu servidor
curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set
na linha 49 
curl_setopt_array($ch, $options);

você saberia como resolver esse erro ?

**Comment by jansenfelipe** [comment]
@tairoroberto dá uma olhada nesse link: http://stackoverflow.com/a/6918685
