### ISSUE TITLE
Erro ao instalar no Laravel 5.2

### ISSUE THREAD

**Issue by danielcmm** [jansenfelipe/cnpj-gratis#16]
Ao rodar o comando composer require jansenfelipe/cnpj-gratis, ocorre o seguinte erro:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jansenfelipe/cnpj-gratis v2.0.0 requires fabpot/goutte 2.0._@dev -> satisfiable by fabpot/goutte[v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4].
    - jansenfelipe/cnpj-gratis v2.0.1 requires fabpot/goutte 2.0._@dev -> satisfiable by fabpot/goutte[v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4].
    - jansenfelipe/cnpj-gratis v2.0.2 requires fabpot/goutte 2.0._@dev -> satisfiable by fabpot/goutte[v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4].
    - jansenfelipe/cnpj-gratis v2.0.3 requires fabpot/goutte 2.0._@dev -> satisfiable by fabpot/goutte[v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4].
    - jansenfelipe/cnpj-gratis v2.0.4 requires fabpot/goutte 2.0._@dev -> satisfiable by fabpot/goutte[v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4].
    - jansenfelipe/cnpj-gratis v2.0.5 requires fabpot/goutte 2.0._@dev -> satisfiable by fabpot/goutte[v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4].
    - fabpot/goutte v2.0.4 requires symfony/css-selector ~2.1 -> no matching package found.
    - fabpot/goutte v2.0.3 requires symfony/css-selector ~2.1 -> no matching package found.
    - fabpot/goutte v2.0.2 requires symfony/css-selector ~2.1 -> no matching package found.
    - fabpot/goutte v2.0.1 requires symfony/css-selector ~2.1 -> no matching package found.
    - fabpot/goutte v2.0.0 requires symfony/css-selector ~2.1 -> no matching package found.
    - Installation request for jansenfelipe/cnpj-gratis ^2.0 -> satisfiable by jansenfelipe/cnpj-gratis[v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4, v2.0.5].

No meu composer.json já tem a lib symfony/css-selector na versão ~3.0.

**Comment by jansenfelipe** [comment]
@danielcmm tenta colocando no seu composer.json o symfony/css-selector na versão ~2.1
