### ISSUE TITLE
Exibir Inscrição estadual?

### ISSUE THREAD

**Issue by REDIDSOFT** [jansenfelipe/cnpj-gratis#17]
Boa tarde, existe alguma forma de recuperar a inscrição estadual?

**Comment by brunogoncalves** [comment]
A inscrição estadual poderá ser visto pelo sintegra mas cada estado tem o
seu site
Em 15/02/2016 16:22, "Jose Ricardo Aviles" notifications@github.com
escreveu:

**Comment by jansenfelipe** [comment]
Temos algumas UF's implementadas https://github.com/SintegraPHP

Dá uma olhada!

**Comment by REDIDSOFT** [comment]
Ow Brazil a base de ICMS é estadual, q mancada hein achei q com a nfe isso ia ser unificado, pena :( Obrigado pela ajuda e excelente trabalho, sucesso!
