### ISSUE TITLE
Parou de funcionar

### ISSUE THREAD

**Issue by eduardoazevedo3** [jansenfelipe/cnpj-gratis#23]
Felipe, estou usando sua biblioteca, que por sinal é muito boa, mas infelizmente ela parou de funcionar, parece que Receita Federal mudou alguma configuração no servidor.

Veja o exemplo que está no seu blog:
http://supliu.com.br/cadastro-empresa

**Comment by Marciobds** [comment]
Bom dia,

estive verificando o motivo de ter parado de funcionar e fiz uma alteração no arquivo
src/CnpjGratis.php adicionando **> div** após o **body** na chamada de **filter** conforme segue abaixo:

**linha 101:**
if ($crawler->filter('body **> div** > table:nth-child(3) > tr:nth-child(2) > td > b > font')->count() > 0)

**linha 104:**
$td = $crawler->filter('body **> div** > table:nth-child(3) > tr > td');

Isto resolveu para mim.

**Comment by jansenfelipe** [comment]
@Marciobds pode mandar um PR com a correção? Value amigo!!

**Comment by brunogoncalves** [comment]
Fiz a alteração aqui tb e funcionou, por favor coloquem a correção na branch 2.0 para que no próximo composer update já esteja tudo certo

**Comment by Marciobds** [comment]
@jansenfelipe feito pull request.
Abraço

**Comment by eduardoazevedo3** [comment]
Funcionou perfeitamente, vlw.

Vou marcar como finalizado essa discussão.

**Comment by jansenfelipe** [comment]
Obrigado @eduardoazevedo3 @Marciobds @brunogoncalves 

Versão 2.0.7 publicada com a correção
